name: Test CI/CD Pipeline

permissions:
  security-events: write
  actions: read
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install frontend dependencies
        run: npm ci

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Lint frontend
        run: npm run lint
        continue-on-error: true

      - name: Build frontend
        run: npm run build

      - name: Run frontend tests (if present)
        run: npm test || echo "No frontend tests defined."
        continue-on-error: true

      - name: Run backend tests (if present)
        run: |
          cd backend
          npm test || echo "No backend tests defined."
        continue-on-error: true

      - name: Run npm audit (frontend)
        run: npm audit --audit-level=high || true

      - name: Run npm audit (backend)
        run: |
          cd backend
          npm audit --audit-level=high || true

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Secure Voting System'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.json'
          format: 'json'

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/dependency-check-report.html
          retention-days: 30

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.json
          retention-days: 30

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read



